// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://rbwyiqonmmfjgcqlbzbx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJid3lpcW9ubW1mamdjcWxiemJ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2NjcwNzcsImV4cCI6MjA3NDI0MzA3N30.IlRDwlcDKeO7WgXXkPLmJV78FSYhyjE3hwy3_rkB26U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});